#!/bin/bash
#
# Copyright (c) 2012 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

set -e

NAME=openxt-pv-audio
PACKAGE=${NAME}-dkms
VERSION=1.0
SRCS=/usr/src/${PACKAGE}-${VERSION}

# Usage: do_dkms_stage stage name version
do_dkms_stage()
{
    local stage="$1"
    local pkg="$2"
    local ver="$3"

    dkms $stage -m $pkg -v $ver
}

pushd ${SRCS}
    echo "${PACKAGE}-${VERSION} installing ..."

    do_dkms_stage add ${PACKAGE} ${VERSION}
    do_dkms_stage build ${PACKAGE} ${VERSION}
    do_dkms_stage install ${PACKAGE} ${VERSION}
    echo "${PACKAGE}-${VERSION} installed."

popd

exit 0
